spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/financial_tracing_db
    password: root123
    username: postgres

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 1234