server:
  port: ${SERVER_PORT}
  shutdown: graceful
spring:
  application:
    name: ${APPLICATION_NAME}
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${POSTGRESQL_URL}
    password: ${POSTGRESQL_PASSWORD}
    username: ${POSTGRESQL_USERNAME}

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
